# Homework 1 - Car Fuel Efficiency 2026

In [2]:
import pandas as pd
import numpy as np

## Q1. Pandas version

In [3]:
pd.__version__

'3.0.6'

## Getting the data

In [4]:
df = pd.read_csv("../../data/car_fuel_efficiency_2026.csv")
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0


## Q2. Records count

In [5]:
len(df)

10000

## Q3. Fuel types

In [6]:
df["fuel_type"].nunique()

3

In [7]:
df["fuel_type"].value_counts()

fuel_type
Gasoline    6913
Diesel      2053
Hybrid      1034
Name: count, dtype: int64

## Q4. Missing values

How many columns have missing values?

In [8]:
missing = df.isnull().sum()
print(missing[missing > 0])
(missing > 0).sum()

horsepower      877
acceleration    264
dtype: int64


np.int64(2)

## Q5. Max fuel efficiency (cars from Asia)

In [9]:
df[df["origin"] == "Asia"]["fuel_efficiency_mpg"].max()

np.float64(41.2)

## Q6. Median value of horsepower

1. Median of `horsepower`
2. Most frequent value (mode) of `horsepower`
3. Fill missing values with the **mode**
4. Median again _ has it changed?

In [10]:
median_before = df["horsepower"].median()
median_before

np.float64(254.0)

In [11]:
most_frequent = df["horsepower"].mode()[0]
most_frequent

np.float64(252.0)

In [12]:
hp = df["horsepower"].fillna(most_frequent)
median_after = hp.median()
print("before:", median_before, "after:", median_after)


df["horsepower"] = hp

before: 254.0 after: 252.0


## Q7. Sum of weights


In [13]:
df_asia = df[df["origin"] == "Asia"]
X = df_asia[["vehicle_weight", "model_year"]].head(7).values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [14]:
XTX = X.T @ X
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [15]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
w = XTX_inv @ X.T @ y
w

array([0.13644777, 0.2327492 ])

In [16]:
w.sum()

np.float64(0.36919696904925486)